### ISSUE TITLE
Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/FTPLtd#8]
# Localization - ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[pr-br.cfg] 🗃️

### Translation

* [x] ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/BR.png "Brazil"

this file: © All Rights Reserved by zer0Kerbal

**Comment by zer0Kerbal** [comment]
@Lisias

**Comment by Lisias** [comment]
Done on https://github.com/zer0Kerbal/FTPLtd/pull/39
